### PR TITLE
Add TrueUSD

### PR DESCRIPTION
**Pull request by chrisqiutusd**
Please help onboard TrueUSD to opBNB chain.

### CODE REVIEW

**Comment by huihzhao** [comment]
Please provide your tg handle so that we can have a quick conversation about this requests.

**Comment by qiwihui** [comment]
> Please provide your tg handle so that we can have a quick conversation about this requests.

`qiwihui`

**Comment by chrisqiutusd** [comment]
> Please provide your tg handle so that we can have a quick conversation about this requests.

`qiwihui`

**Comment by chrisqiutusd** [comment]
> Please provide your tg handle so that we can have a quick conversation about this requests.

any update?

**Review by huihzhao — APPROVED** [review]

**Pull request closed without merging**
