### PR TITLE
add token XCAD

### PR DESCRIPTION
**Pull request by owen-reorg**
update opBNB mainnet data with new token - fbd20c4c21c380dc8989e8d6b000b9e1034e03dc

### CODE REVIEW

**Review by xiangdotli — APPROVED** [review]
- https://opbnbscan.com/token/0xAF9fE3B5cCDAe78188B1F8b9a49Da7ae9510F151
- 
https://opbnbscan.com/address/0xc5098ce789965A19A17987e02b0F789E65A21F16?tab=withdraw&p=1

**Comment by owen-reorg** [comment]
LGTM

**Review by rickyyangz — APPROVED** [review]

**Review by huihzhao — APPROVED** [review]

**Comment by ChrisXXXXXXX** [comment]
passed the security check

**Review by ChrisXXXXXXX — APPROVED** [review]
passed the security check

**Pull request merged**
